[package]
name = "decay_codegen"
version = "0.1.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]
license = "MIT/Apache-2.0"

[dependencies]
#git2 = "0.3"
aster = "0.30.0"
quasi = "0.22.0"
quasi_macros = { version = "0.22.0", optional = false }
