[package]
name = "decay_macros"
version = "0.1.0"
authors = ["Jeremy Letang <letang.jeremy@gmail.com>"]
license = "MIT/Apache-2.0"

[lib]
name = "decay_macros"
plugin = true

[dependencies]
decay_codegen = { version = "*", path = "../decay_codegen" }
